// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/bj38/bj38.proto

package go_micro_srv_bj38

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Bj38 service

type Bj38Service interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Bj38_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Bj38_PingPongService, error)
}

type bj38Service struct {
	c    client.Client
	name string
}

func NewBj38Service(name string, c client.Client) Bj38Service {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.bj38"
	}
	return &bj38Service{
		c:    c,
		name: name,
	}
}

func (c *bj38Service) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Bj38.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bj38Service) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Bj38_StreamService, error) {
	req := c.c.NewRequest(c.name, "Bj38.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &bj38ServiceStream{stream}, nil
}

type Bj38_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type bj38ServiceStream struct {
	stream client.Stream
}

func (x *bj38ServiceStream) Close() error {
	return x.stream.Close()
}

func (x *bj38ServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *bj38ServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *bj38ServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bj38Service) PingPong(ctx context.Context, opts ...client.CallOption) (Bj38_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Bj38.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &bj38ServicePingPong{stream}, nil
}

type Bj38_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type bj38ServicePingPong struct {
	stream client.Stream
}

func (x *bj38ServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *bj38ServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *bj38ServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *bj38ServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *bj38ServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Bj38 service

type Bj38Handler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Bj38_StreamStream) error
	PingPong(context.Context, Bj38_PingPongStream) error
}

func RegisterBj38Handler(s server.Server, hdlr Bj38Handler, opts ...server.HandlerOption) error {
	type bj38 interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Bj38 struct {
		bj38
	}
	h := &bj38Handler{hdlr}
	return s.Handle(s.NewHandler(&Bj38{h}, opts...))
}

type bj38Handler struct {
	Bj38Handler
}

func (h *bj38Handler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.Bj38Handler.Call(ctx, in, out)
}

func (h *bj38Handler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.Bj38Handler.Stream(ctx, m, &bj38StreamStream{stream})
}

type Bj38_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type bj38StreamStream struct {
	stream server.Stream
}

func (x *bj38StreamStream) Close() error {
	return x.stream.Close()
}

func (x *bj38StreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *bj38StreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *bj38StreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *bj38Handler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.Bj38Handler.PingPong(ctx, &bj38PingPongStream{stream})
}

type Bj38_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type bj38PingPongStream struct {
	stream server.Stream
}

func (x *bj38PingPongStream) Close() error {
	return x.stream.Close()
}

func (x *bj38PingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *bj38PingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *bj38PingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *bj38PingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
